export const GET_EXAM_REQUEST   = 'GET_EXAM_REQUEST';
export const GET_EXAM_SUCCESS   = 'GET_EXAM_SUCCESS';
export const GET_EXAM_FAIL      = 'GET_EXAM_FAIL';

export const EXAM_SUBMIT_REQUEST= 'EXAM_SUBMIT_REQUEST';
export const EXAM_SUBMIT_SUCCESS= 'EXAM_SUBMIT_SUCCESS';
export const EXAM_SUBMIT_FAIL   = 'EXAM_SUBMIT_FAIL';

export const EXAM_RESET         = 'EXAM_RESET';
export const GET_EXAM_DETAILS   = 'GET_EXAM_DETAILS';

export const GET_RESPONSE             = 'GET_RESPONSE';
export const RESET_RESPONSE           = 'RESET_RESPONSE';
export const UPDATE_RESPONSE          = 'UPDATE_RESPONSE';
export const SUBMIT_RESPONSE_REQUEST  = 'SUBMIT_RESPONSE_REQUEST';
export const SUBMIT_RESPONSE_SUCCESS  = 'SUBMIT_RESPONSE_SUCCESS';
export const SUBMIT_RESPONSE_FAIL     = 'SUBMIT_RESPONSE_FAIL';


