export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_VERFIY_RESEND = 'USER_VERIY_RESEND';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_VERIFY_SUCCESS = 'USER_VERIFY_SUCCESS';
export const USER_PASSWORD_RESET_COMPLETE = 'USER_PASSWORD_RESET_COMPLETE';
export const USER_PASSWORD_RESET_FAIL = 'USER_PASSWORD_RESET_FAIL';
export const USER_PASSWORD_RESET_REQUEST = 'USER_PASSWORD_RESET_REQUEST';
export const USER_PASSWORD_RESET_SUCCESS = 'USER_PASSWORD_RESET_SUCCESS';

export const ADD_PROFILE_REG_DATA = 'ADD_PROFILE_REG_DATA';
export const ADD_PROFILE_REG_ADDRESS_DATA = 'ADD_PROFILE_REG_ADDRESS_DATA';
export const ADD_PROFILE_REG_RES_ADDRESS_DATA =
    'ADD_PROFILE_REG_RES_ADDRESS_DATA';
export const ADD_PROFILE_REG_SCHOOL_DATA = 'ADD_PROFILE_REG_SCHOOL_DATA';

export const USER_LOGOUT = 'USER_LOGOUT';
