export { default as Signin } from './SigninPage';
export { default as Signup } from './SignupPage';
export { default as Verify } from './VerificationPage';
export { default as NotFound } from './NotFoundPage';
export { default as Register } from './RegistrationPage';
export { default as Dashboard } from './Dashboard';
export { default as Reset } from './ResetPassword';
export { default as Exam } from './ExamPage';
export { default as UserAuth } from './UserAuthPage';
